# 配置开发环境logging:

jdbc:
  url: jdbc:mysql://localhost:3306/test_springboot?useUnicode=true&characterEncoding=utf8
  driver: com.mysql.jdbc.Driver
  userName: root
  passWord: root123

datasource:
  url: ${jdbc.url}
  username: ${jdbc.userName}
  password: ${jdbc.passWord}